### ISSUE TITLE
Exemplo usando Bun

### ISSUE THREAD

**Issue by fcrespo82** [gabrielfroes/sorteio-websocket#1]
Boa tarde @gabrielfroes.

Já sou desenvolvedor a muito tempo mas nunca precisei utilizar _websockets_, assisti o vídeo de vocês sobre o projeto e achei muito interessante.

Aproveitando o _hype_ do Bun, fiz um [fork do projeto](https://github.com/fcrespo82/sorteio-websocket-bun) e migrei o `server.js` para utilizar a API padrão dele.

Abraço e continuem fazendo esse ótimo trabalho de ensinar.

**Comment by gabrielfroes** [comment]
Sensacional @fcrespo82! Minha ideia era realmente portar para o Bun e fazer algumas comparações. Vou analisar sua versão e colocar para rodar por aqui. Agradeço sua contribuição e por nos acompanhar.

**Comment by fcrespo82** [comment]
Usei as APIs internas e mudei o código o mínimo possível.

Também usei o mínimo de dependência possível. É possível retirar a única que usei, mas achei que trazia um benefício igual ao do express.static.

Caso queira posso substituir pelo código nativo, mas não acho que seja imprescindível para a comparação.
